# Generated by Django 4.2.4 on 2025-12-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_optiongroup_productclass_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='options',
            field=models.ManyToManyField(to='catalog.option'),
        ),
    ]
