# Generated by Django 4.2.4 on 2025-12-04 13:23

from django.db import migrations, models
import django.db.models.deletion
import djshop.libs.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.option'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(choices=[('standalone', 'Standalone'), ('parent', 'Parent'), ('child', 'Child')], default='standalone', max_length=16)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('upc', djshop.libs.db.fields.UpperCaseCharField(blank=True, max_length=24, null=True, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=128, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
